saving: true
saving_path: # keep None, will be created automatically with timestamp
train_dataset:
  num_samples: 4
  augmentation: align
  balance_classes: false
  requested_sequences:
  - 4
val_dataset:
  num_samples: 80
  augmentation: align
  balance_classes: false
  requested_sequences:
  - 4
  in_R: 51
model:
  name: VNDGCNN
  pretrained_weights: false
  freeze_head_weights: false
  ckpt_path: ./pretrained_weights/vn_dgcnn/best_chkp.tar
train_loader:
  shuffle: false
  batch_size: 4
  num_workers: 4
  pin_memory: true
val_loader:
  shuffle: false
  batch_size: 1
  num_workers: 1
  pin_memory: true
trainer:
  saving: ${saving}
  saving_path: ${saving_path}
  style: train
  task: pls
  lr_decays: null
  var_lr: 0.1
  momentum: 0.98
  optimizer:
    name: adam
    learning_rate: 0.0001
    weight_decay: 0
  # lr_scheduler: #TODO: remove commented out code for schedulers to use them again !
    # milestones:
    # - 50
    # - 50
    # - 300
    # gamma: 0.5
  free_dim: 4
  max_epoch: 3000
  grad_clip_norm: 0.0
  class_w: []
