dataset:
model:
trainer:
  learning_rate: 1e-3
  lr_decays: #dynamic calculations
  momentum: 0.98
  weight_decay: 1e-3
  free_dim: 4
  var_lr: 1e-3
  # saving:
  max_epoch: 1000
  grad_clip_norm: 100.0

